"""Public API entry point for algo_sdk."""

from .algorithm_api.decorators import Algorithm
from .core import (
    AlgorithmRegistry,
    AlgorithmSpec,
    AlgorithmType,
    BaseAlgorithm,
    BaseModel,
    ExecutionConfig,
    ExecutionError,
    ExecutionMode,
    ExecutionRequest,
    ExecutionResult,
    ExecutorProtocol,
    InProcessExecutor,
    ProcessPoolExecutor,
    IsolatedProcessPoolExecutor,
    DispatchingExecutor,
    get_registry,
    AlgorithmLifecycleProtocol,
)
from .http import AlgorithmHttpService, ObservationHooks
from .protocol import (
    AlgorithmContext,
    AlgorithmRequest,
    AlgorithmResponse,
    api_error,
    api_success,
)
from .runtime import (
    build_service_runtime,
    execution_context,
    get_current_context,
    get_current_request_id,
    get_current_trace_id,
    get_current_request_datetime,
    set_response_code,
    set_response_message,
    set_response_context,
    get_response_meta,
)

__all__ = [
    "Algorithm",
    "BaseModel",
    "AlgorithmContext",
    "AlgorithmRequest",
    "AlgorithmResponse",
    "api_success",
    "api_error",
    "AlgorithmRegistry",
    "AlgorithmSpec",
    "AlgorithmType",
    "ExecutionConfig",
    "ExecutionMode",
    "ExecutionError",
    "ExecutionRequest",
    "ExecutionResult",
    "ExecutorProtocol",
    "InProcessExecutor",
    "ProcessPoolExecutor",
    "IsolatedProcessPoolExecutor",
    "DispatchingExecutor",
    "AlgorithmHttpService",
    "ObservationHooks",
    "build_service_runtime",
    "execution_context",
    "get_current_context",
    "get_current_request_id",
    "get_current_trace_id",
    "get_current_request_datetime",
    "set_response_code",
    "set_response_message",
    "set_response_context",
    "get_response_meta",
]
